mollie/Shopware6

- src/Resources/config/services.xml
- src/Resources/snippet/de_DE/SnippetFile_de_DE.php
- src/Resources/snippet/de_DE/mollie.components.creditcard.de-DE.json
Hi, I added german translations for the credit card form.
> added german translations for credit card form

- composer.json
- src/Factory/MollieApiFactory.php
- src/Service/OrderService.php
**Bugfix:**
- Fixed an issue where custom products would cause an error.
> Fixed an issue with custom products.

- src/Helper/OrderStateHelper.php
if nothing should be done (status skip) we won't set any stati and return
> MOL-140: fix order state handling if skipped is configured

- src/Exception/MissingPriceLineItemException.php
- src/Facade/MollieShipment.php
- src/Resources/config/services.xml
- src/Resources/config/services/subscriber.xml
- src/Service/CustomFieldsInterface.php
- src/Service/MollieApi/Order.php
- src/Service/MolliePaymentExtractor.php
- src/Service/OrderDeliveryService.php
- src/Service/OrderService.php
- src/Subscriber/OrderDeliverySubscriber.php
- src/Validator/OrderLineItemValidator.php
- tests/Facade/MollieShipmentTest.php
- tests/Service/MolliePaymentExtractorTest.php
- tests/Service/OrderServiceTest.php
> refactoring shipment api call

- .github/workflows/README.md
- .github/workflows/ci_pipe.yml
- .gitignore
- composer.json
- composer.lock
- makefile
- phpstan.neon
- phpunit.xml
- readme.md
...have fun...just have fun with it ;)
> NTR: Github Actions + PHPStan

- src/Handler/Method/BankTransferPayment.php
Currently the payment specific handlers are deactivated in PaymentHandler line 596. But when I activated the BankTransferPayment handler for a customer I realized a few Problems:
- the payment->billingEmail Parameter is invalid for orders API and throws an API Exception
- the payment->locale Parameter is invalid for orders API and throws an API Exception
- the payment->dueDate Parameter has no effect in orders API, therefor the order->expiresAt Parameter has to be set
Although this payment handler is not used currently a correction of these problems now makes sense so that they aren't forgotten when payment specific handlers are reactivated, or the BankTransferPayment handler could be reactivated in one of the sooner releases to enable different Due Dates for this much longer taking …
> MOL-364: Corrected BankTransferPayment Handler

- .github/workflows/README.md
- .github/workflows/pr_pipe.yml
split pipelines in preparation for cypress tests
> NTR: separate CI and PR pipelines

- src/Service/CustomerService.php
- src/Subscriber/CustomerRegistrationSubscriber.php
removed db call for better performance
> performance improvements

- .github/workflows/ci_pipe.yml
- .github/workflows/pr_pipe.yml
- phpinsights.php
> NTR: update PHPInsights minimum levels

- README.md
i did remove that one
also changed it to be an upper case README.md, hope its ok
> NTR: remove ING Home’Pay from README, add Apple Pay

- tests/Cypress/cypress/integration/storefront/checkout/checkout-full.spec.js
- tests/Cypress/cypress/support/actions/storefront/products/PDPAction.js
- tests/Cypress/cypress/support/repositories/storefront/products/PDPRepository.js
add more cypress tests
had to do dynamic quantites because klarna slice it needs a higher total amount in general
> MOL-429: add sliceit and banktransfer to cypress tests

- .github/workflows/ci_pipe.yml
- .github/workflows/pr_pipe.yml
- composer.json
- composer.lock
- makefile
add php minimum check for php 7.2 to plugin and pipelines
> NTR: add php minimum check to pipeline

- .github/workflows/ci_pipe.yml
add missing dependency install in cypress github action for plugin
> MOL-429: install dependencies in cypress github pipeline

- composer.json
- composer.lock
- src/Handler/PaymentHandler.php
- src/Service/WebhookBuilder/WebhookBuilder.php
- tests/PHPUnit/Fakes/FakeRouter.php
- tests/PHPUnit/Service/WebhookBuilder/WebhookBuilderTest.php
support for services like NGROK
set a custom domain with env variable
its called custom "domain" and not "webhook domain" because we will need it also for upcoming apple pay local environments :)
> MOL-447: NGROK Support for Webhook URLs

- .phpstan.neon
- src/Handler/PaymentHandler.php
- src/Storefront/Controller/ApplePayDirectController.php
removed the 3 excluded folders of phpstan
and applied some easy fixes for these
> NTR: PHPStan LvL1 Fixes

- .phpstan.lvl8.neon
- makefile
- src/Factory/MollieApiFactory.php
- src/MolliePayments.php
add separate lvl8 checks of phpstan for some folders
> NTR: add phpstan lvl8 for some folders

- src/Helper/PaymentStatusHelper.php
klarna payments have not been updated
the comlete was missing
please note, the $paidNumber part, which is coming later in that file did also not work....not at all....
so I've decided to add that required part in the first if-condition, and just keep that other weird part untouched
> MOL-430: Fix paid Klarna orders not updated trough webhooks

- src/Facade/Notifications/NotificationFacade.php
- src/Factory/MollieApiFactory.php
- src/Gateway/Mollie/MollieGateway.php
- src/Gateway/MollieGatewayInterface.php
- src/Resources/config/services.xml
- src/Resources/config/services/gateways.xml
- src/Service/Mollie/MolliePaymentStatus.php
- src/Service/Mollie/OrderStatusConverter.php
- src/Service/Order/OrderStatusUpdater.php
- src/Storefront/Controller/WebhookController.php
- tests/PHPUnit/Service/Mollie/MolliePaymentStatusTest.php
completely refactored the webhooks in order to correctly update all payment status possibilities
> MOL-453: Refactor Webhook Notifications

- src/Service/MollieApi/Builder/MollieOrderBuilder.php
webhook builder was not used anymore
ngrok does now work again locally
> MOL-555: Fix custom webhook domains from env variable

- src/Service/ShopService.php
- src/Storefront/Controller/ApplePayDirectController.php
-Use RouterInterface instead of concrete Router class
> Use RouterInterface instead of concrete Router class

- .phpstan.lvl8.neon
- .phpstan.neon
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Cache/CachedPaymentMethodRoute64.php
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute62.php
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute63.php
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute64.php
- src/Resources/config/compatibility/services_6.2.xml
- src/Resources/config/compatibility/services_6.3.xml
- src/Resources/config/compatibility/services_6.4.xml
- src/Resources/config/services/services.xml
since shopware 6.4 theres a cache existing for payment methods :D
> MOL-216: Fix problem with cached payment methods for vouchers

- src/Resources/config/services/subscriber.xml
- src/Resources/views/storefront/component/product/card/action.html.twig
- src/Resources/views/storefront/page/product-detail/buy-widget-form.html.twig
- src/Subscriber/ApplePayDirectSubscriber.php
- tests/Cypress/cypress/integration/storefront/checkout/checkout-failed.spec.js
- tests/Cypress/cypress/integration/storefront/checkout/checkout-states.spec.js
- tests/Cypress/cypress/integration/storefront/checkout/checkout-success.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/applepay-direct.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/applepay.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/ideal.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/methods.spec.js
- tests/Cypress/cypress/integration/storefront/payment-methods/vouchers.spec.js
- tests/Cypress/cypress/support/actions/admin/ShopConfigurationAction.js
forms shouldnt be rendered if disabled
margin removal planned when including new twig blocks
> MOL-652: Do not render Apple Pay Direct if disabled

- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components.plugin.js
IE did not work with fetch
so I switched to something "classic" ;)
> MOL-673: Fix Credit Card components for Internet Explorer

- src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/index.js
- src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/sw-order-line-items-grid.html.twig
- src/Resources/app/administration/src/snippet/de-DE.json
- src/Resources/app/administration/src/snippet/en-GB.json
- src/Resources/app/administration/src/snippet/nl-NL.json
- tests/Cypress/cypress/integration/storefront/refund/refund.spec.js
- tests/Cypress/cypress/support/actions/admin/AdminOrdersAction.js
- tests/Cypress/cypress/support/repositories/admin/orders/OrderDetailsRepository.js
add better mollie action button
> MOL-718: Mollie Action button in Administration

- src/Service/CustomerService.php
A totally not useless commit to get rid of first contribution status ;)
> NTR: Use the custom field constant instead

- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-direct.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
This was all the jquery I could find.
> MOL-748: Remove jquery for Shopware 6.5

- src/Resources/snippet/de_DE/mollie-payments.de-DE.json
- src/Resources/snippet/en_GB/mollie-payments.en-GB.json
- src/Resources/snippet/nl_NL/mollie-payments.nl-NL.json
- src/Resources/views/storefront/component/payment/component/ideal-fields.html.twig
Validation is being triggered but no message is shown. I have no idea why that is not happening.
> MOL-784-iDeal-with-default-dropdown-"Select-Bank"

- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/index.js
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/mollie-refund-manager.html.twig
Refunding can be a slow process, which is why I have added a spinner to both refund buttons while refunding. Also simplified the code by removing some duplicate code on refund.
> NTR: Improved refund buttons

- src/Controller/Storefront/Webhook/NotificationFacade.php
- src/Resources/config/services.xml
If after payment the user isn't redirected to Showare because of any reason the customFields haven't been updated.
=> Update customFields on Webhook call
> MOL-837: Update CustomFields in Webhook

- src/Service/CustomerService.php
Added a change that creates a customer when no mollie customer can be found with the current customer/sales channel id combination.
> MOL-771: Customer ID is invalid when creating an order

- src/Controller/Storefront/Webhook/NotificationFacade.php
Added associations for mail templates
> MOL-907 Flow Builder Mollie Webhooks not compatible with Order Confirmation Mail

- src/Service/MollieApi/Builder/MollieShippingLineItemBuilder.php
Fixes the Issue [#553](https://github.com/mollie/Shopware6/issues/553)
> Fixes #553

- polyfill/Shopware/Core/Framework/Event/OrderAware.php
> NTR: Check for `OrderAware` interface

- src/Resources/views/storefront/component/buy-widget/buy-widget-form.html.twig
- src/Resources/views/storefront/component/product/card/action.html.twig
- src/Resources/views/storefront/page/checkout/address/register.html.twig
- src/Resources/views/storefront/page/product-detail/buy-widget-form.html.twig
- src/Struct/Product/ProductAttributes.php
- tests/PHPUnit/Service/Cart/Voucher/VoucherServiceTest.php
- tests/PHPUnit/Struct/Product/ProductAttributesTest.php
>  PISHPS-273: fix subscription button in diffferent languages

- src/Handler/Method/MyBankPayment.php
- src/Resources/config/services/handlers.xml
- src/Service/PaymentMethodService.php
- tests/PHPUnit/Service/MollieApi/Builder/Payments/MyBankOrderBuilderTest.php
- tests/PHPUnit/Service/PaymentMethodServiceTest.php
> PISHPS-281 MyBank payment

- src/Resources/config/services/services.xml
- src/Service/Logger/MollieLoggerFactory.php
> Check for database connection during logger creation instead of dsn

- src/Resources/config/services/scheduled_tasks.xml
- src/ScheduledTask/OrderStatus/ExpireOrderTaskHandler.php
- src/ScheduledTask/Subscription/RenewalReminder/AbstractRenewalReminderTaskHandler.php
- src/ScheduledTask/Subscription/RenewalReminder/RenewalReminderTaskDevHandler.php
- src/ScheduledTask/Subscription/RenewalReminder/RenewalReminderTaskHandler.php
- fixed memory issue of ExpireOrderTaskHandler
- fixed stan error attribute not repeatable
> PISHPS-348: memory issue + phpstan

- src/Controller/Api/Order/CancelLineController.php
- src/ScheduledTask/OrderStatus/ExpireOrderTaskHandler.php
- reduced log output of ExpireOrderTaskHandler
- added type check to CancelLineController
> PISHPS-350 type check to CancelLineController

- LICENCE.md
> NTR: add licence

- .phpstan.neon
- composer.json
- composer.lock
- polyfill/Shopware/Core/Checkout/Payment/Exception/PaymentProcessException.php
- polyfill/Shopware/Core/Checkout/Payment/PaymentException.php
- polyfill/Shopware/Core/Framework/Event/BusinessEventInterface.php
- polyfill/Shopware/Core/Framework/Event/CustomerAware.php
- polyfill/Shopware/Core/Framework/Event/FlowEventAware.php
- polyfill/Shopware/Core/Framework/Event/MailActionInterface.php
- polyfill/Shopware/Core/Framework/Event/MailAware.php
- polyfill/Shopware/Core/Framework/Event/OrderAware.php
- polyfill/Shopware/Core/System/Snippet/Files/AbstractSnippetFile.php
- polyfill/Shopware/Core/System/Snippet/Files/SnippetFileInterface.php
- src/Compatibility/DependencyLoader.php
- src/MolliePayments.php
> PISHPS-373: Polyfills

- src/Components/PaypalExpress/PayPalExpress.php
- src/Components/PaypalExpress/Route/FinishCheckoutRoute.php
- src/Controller/Storefront/PaypalExpress/PaypalExpressControllerBase.php
- src/Repository/PaymentMethod/PaymentMethodRepository.php
- src/Repository/PaymentMethod/PaymentMethodRepositoryInterface.php
- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-direct.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/mollie-express-actions.plugin.js
- src/Resources/app/storefront/src/mollie-payments/services/ApplePaySessionFactory.js
- src/Resources/app/storefront/src/scss/base.scss
- src/Resources/app/storefront/src/scss/component/express-button.scss
- src/Resources/snippet/de_DE/mollie-payments.de-DE.json
- src/Resources/snippet/en_GB/mollie-payments.en-GB.json
- src/Resources/snippet/it_IT/mollie-payments.it-IT.json
- src/Resources/snippet/nl_NL/mollie-payments.nl-NL.json
- src/Resources/views/mollie/component/paypal-express-button.twig
- tests/PHPUnit/Fakes/Repositories/FakePaymentMethodRepository.php
- added loader to the button
- button cannot be triggered multiple times
- show PPE only if added to saleschannel
- add error after failed payment
> NTR: some changes

- src/Service/Payment/Remover/RegularPaymentRemover.php
> NTR: hide billie without company fix #904

- CHANGELOG.md
- polyfill/Shopware/Core/Checkout/Cart/CartException.php
- src/Controller/Api/PluginConfig/Services/MollieRefundConfigService.php
- src/Controller/Storefront/Webhook/NotificationFacade.php
- src/Service/OrderService.php
> NTR: Fix the issue with order not found exception

- tests/Cypress/cypress/support/actions/storefront/account/LoginAction.js
had troubles in earlier times when reusing sessions
but its looks better now
> NTR: add cypress login to session shared across specs

- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-support-modal/mollie-pluginconfig-support-modal.html.twig
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-support-modal/mollie-pluginconfig-support-modal.scss
this is just a really quick fix
> NTR: fix broken admin support form buttons

- src/Components/CancelManager/CancelItemFacade.php
- tests/PHPUnit/Components/CancelManager/CancelItemFacadeTest.php
- tests/PHPUnit/Fakes/CancelItemFacadeBuilder.php
> NTR: fix cancel line items

- src/Resources/app/storefront/src/mollie-payments/core/creditcard-mandate.plugin.js
- src/Resources/app/storefront/src/mollie-payments/helper/csrf-ajax-mode.helper.js
- src/Resources/app/storefront/src/mollie-payments/helper/device-detection.helper.js
- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-direct.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-payment-method.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/bancomat-plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-mandate-manage.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/mollie-express-actions.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/paypal-express.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/pos-terminal.plugin.js
- src/Resources/app/storefront/src/mollie-payments/services/apple-pay-session-factory.service.js
- src/Resources/app/storefront/src/mollie-payments/services/express-add-to-cart.service.js
- src/Resources/app/storefront/src/mollie-payments/services/http-client.service.js
- src/Resources/app/storefront/tests/service/CsrfMode.spec.js
- src/Resources/views/storefront/page/account/payment/index.html.twig
- src/Resources/views/storefront/page/checkout/cart/index.html.twig
- src/Resources/views/storefront/page/checkout/confirm/index.html.twig
- clean up selector handling in plugin code
- move files to more fitting folders & adjust their names
> NTR: storefront js plugin code cleanup & improvement

- CHANGELOG.md
- src/Components/ApplePayDirect/ApplePayDirect.php
- src/Controller/Storefront/Webhook/NotificationFacade.php
- src/Facade/MolliePaymentFinalize.php
- src/Repository/OrderTransactionRepository.php
- src/Service/CustomFieldsInterface.php
- src/Service/OrderService.php
- src/Struct/OrderTransaction/OrderTransactionAttributes.php
- tests/PHPUnit/Struct/OrderTransaction/OrderTransactionAttributesTest.php
> PISHPS-505: fix for webhooks which are triggered too early

- CHANGELOG.md
- src/Components/Subscription/Services/SubscriptionRenewing/OrderCloneService.php
> NTR: Fix order cloning

- .gitignore
- CHANGELOG.md
- shopware/Component/Payment/PaymentHandlerTrait.php
- src/Components/PaypalExpress/PayPalExpress.php
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/RefundManager.js
- src/Resources/app/storefront/src/mollie-payments/plugins/express/paypal-express.plugin.js
- src/Resources/app/storefront/src/mollie-payments/services/express/add-to-cart.service.js
- src/Resources/app/storefront/src/scss/component/express-button.scss
- src/Resources/config/services.xml
- src/Service/CustomerService.php
- src/Subscriber/PaypalExpressSubscriber.php
- tests/PHPUnit/Service/CustomerServiceTest.php
> PISHPS-503: Show validation errors for guest accounts

- CHANGELOG.md
- config/.phpstan.neon
- src/Compatibility/Storefront/Route/PaymentMethodRoute/RemovePaymentMethodRoute64.php
> PISHPS-514: Fix payment method route in store-api

- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-info/mollie-pluginconfig-section-info.html.twig
- tests/Cypress/cypress/e2e/admin/plugin-config.cy.js
> NTR: fix broken doc link
