mollie/Shopware6

- .gitignore
- src/Helper/PaymentStatusHelper.php
we have to return the failed status even if transition has failed before. Method is called more than one time during payment process
> MOL-140: fix failed transactions redirect if standard shopware handling is active

- src/Resources/config/services.xml
- src/Service/CustomerService.php
This fixes an issue with Apple Pay Direct and the upcoming PayPal Shortcut in 6.3.5+
> FIX: ContextPersister requires saleschannelId in 6.3.4

- src/Service/CartService.php
@schmitzcarsten This PR is in response to the issue you raised in your email.
When creating a LineItem, as is being done in CartService on line 95, stackable is set to false by default. When a promotion is added to the cart, either manually through a coupon or automatically, Shopware tries to calculate the discount by cloning the lineitem according to the quantity (So if quantity is 3 it will create 3 clones of the lineitem) and setting the quantity to 1 on each clone. However, setting the quantity is not possible when stackable is set to false, thus generating the "LineItem is not stackable" error.
Fix is to just set the lineitem to be stackable. 
Note that since the lineitem is created in the cartservice, this should also affect Apple Pay Direct, which uses the same function to add the …
> Fix LineItem not stackable error when a promotion is added to the cart

- phpunit.xml
- src/Setting/MollieSettingStruct.php
- tests/Setting/MollieSettingsStructTest.php
made the methods getOrderLifetimeDays and getOrderLifetimeDate nullable.
in the File Handler/Method/PaymentHandler.php:578-582
there is following line
```php 
$dueDate = $settings->getOrderLifetimeDate();
if ($dueDate !== null) {
$orderData[self::FIELD_EXPIRES_AT] = $dueDate;
}
```
so i assume if the $dueDate is not set it will not send to the api request. if the date is not configured in the plugin settings, this method will return null
> MOL-159: do not send lifetimedays if they are not set in config

- makefile
code coverage is back ;)
added ENV variable export for xdebug 3 and a report in public docroot path to immediately access the html report
> NTR: add code coverage support with report

- src/Exception/PaymentUrlException.php
- src/Handler/PaymentHandler.php
When an API Exception occured the pay method of PaymentHandler did throw a RuntimeException. This Exception Type isn't handled in the Shopware CheckoutController order action and this caused:
- the redirect to finish page didn't work anymore
- the customer did see a page at the checkout/order route which isn't meant to show a frontend page and so it's mostly unstyled
Solution:
Created a new Exception type which is a subclass of PaymentProcessException and so handled by the Shopware CheckoutController order action. Now in case of an API Exception the customer is redirected to checkout/finish and from there to account/order to change the payment method:
> MOL-365: Correct API Exception Handling to reallow Redirect to Finish

- src/Factory/MollieApiFactory.php
- src/Resources/config/services.xml
- src/Subscriber/CheckoutConfirmPageSubscriber.php
if you have a specific configuration (api key) of a single sales channel, then this configuration has not been used.
it was always the MollieApiClient for the configuration for "All Sales Channels"
the origin of the problem was the singleton approach in the factory, i dont know where its created the first time, but it was with the wrong api key
i've tested: 
* before: var_dump with api key in components subscriber showed api key A (all) even though "storefront" had B
* after: var_dump shows api key B if enabled
i've improved the class itself a bit
IMPORTANT!
this factory fix could fix more problems related to refudns and shipping (where it has been used).
but it can also show problems "suddenly" when a merchant has a custom configuration that is wrong...at the moment its actually …
> MOL-377: Fix wrong API key of specific channel in components

- .github/workflows/ci_pipe.yml
artefacts have been excluded by gitignore. We have to create them before integration and e2e tests
> NTR: fix ci pipeline

- .editorconfig
- makefile
Added an editor config file to force .json files to use 2 spaces as indentation. The editor config that comes with the Shopware development template forces everything to 4 spaces, and DIW seems to use 2 spaces. This will force everyone to use 2 spaces for this repository.
> Add editorconfig for json files to force indenting to 2 spaces.

- src/Resources/app/storefront/src/mollie-payments/plugins/ideal-issuer.plugin.js
- src/Resources/views/storefront/component/payment/payment-method.html.twig
- tests/Cypress/cypress/integration/6.4/storefront/checkout/checkout-full.spec.js
added compatible code for shopware >= 6.4 and <
the new code will change the selected iDeal issuer on dropdown value changed
the old code somehow didnt work in 6.3.5.2, so i've changed the event handler from a "form listener" to a "button click" listener, which worked
i also added 2 cypress tests that evaluate that a pre-selected issuer is being sent with the payment request.
in that case, there will immediately be a payment status form instead of an additional issuer-selection list in Mollie
that asserts that an existing issuer has been set
> MOL-461: Fix iDEAL Issuers in Shopware 6.4

- src/Handler/PaymentHandler.php
as discussed, easiest solution at the moment ist to skip that additional GET param
its not used anyway
the return url is fetched from the custom fields in the database
cypress is green, so payments do at least work
> MOL-494: Remove unnecessary long redirect url

- README.md
We have received an increased number of support requests concerning this. People (including me) always forget to assign the Mollie payment methods to the storefront, so it might make sense to have it in the docs.
> Add assignment to storefronts to docs

- src/Controller/Api/OrderController.php
- src/Controller/Api/RefundController.php
- src/Controller/Api/ShippingController.php
- src/Exception/MissingSalesChannelInOrder.php
- src/Facade/MollieShipment.php
- src/Facade/Notifications/NotificationFacade.php
- src/Facade/SetMollieOrderRefunded.php
- src/Service/MollieApi/Order.php
- src/Subscriber/OrderDeliverySubscriber.php
- src/Subscriber/PaymentStateSubscriber.php
- src/Subscriber/TestModeNotificationSubscriber.php
- tests/Cypress/package.json
- tests/PHPUnit/Facade/MollieShipmentTest.php
- tests/PHPUnit/Facade/SetMollieOrderRefundedTest.php
in SW versions < 6.3 there is no method getSalesChannelId in SalesChannelContext
> MOL-504: add backwards compatibility

- src/Storefront/Controller/PaymentController.php
somehow the url parameter isnt valid anymore in the latest shopware version.
as soon as there is an encoded :// in there from http....then its somewhere caught from the router
and this leads to a Not Found page
so i just removed the param and added the url as GET parameter,
Cypress is now green again locally
> MOL-572: Fix broken Retry Payment Not Found error

- src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/index.js
In a shop for a client, I was having an issue when using mollie credit card payment that the order items in the order details was not showing up in the admin section. The error was giving an "undefined" error at this point when reading the length property. Adding an additional check here for refunds array if it is available before checking for length solves the problem.
> Add check for refunds array if it is not undefined

- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute62.php
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute63.php
- src/Compatibility/Storefront/Route/PaymentMethodRoute/Voucher/HideVoucherPaymentMethodRoute64.php
- src/Resources/config/compatibility/services_6.2.xml
- src/Resources/config/compatibility/services_6.3.xml
- src/Resources/config/compatibility/services_6.4.xml
due to some looooong dependency chains, theres a circular reference.
the only option is to change to lazy-loading for the CartService.
The cart service unfortunately reloads the decorated CartRule of Acris...which leads to our problem.
> MOL-632: Plugin Compatibility Acris Shipping Preselect

- .gitignore
Similar to the compiled JS, the compiled CSS should also not be in the repository, but should be built before preparing a release.
> NTR: Ignore compiled admin css

- .gitignore
- src/Resources/app/administration/package.json
- src/Resources/app/storefront/package.json
Another small update to ignore node_modules when all the dev dependencies are installed.
#219 is on the roadmap so package-lock.json is not ignored.
> NTR: Ignore node modules in administration and storefront

- src/Facade/MolliePaymentFinalize.php
- src/Handler/PaymentHandler.php
- tests/Cypress/cypress/integration/storefront/checkout/checkout-states.spec.js
- tests/Cypress/makefile
with the shopware default behaviour for failed payments,
the failed payments lead to a status "cancelled".
so we only do this if its really cancelled,
otherwise it should be an exception that leads to the status "failed"
> MOL-635: Failed payments have status cancelled instead of failed

- src/Resources/config/services/services.xml
- src/Service/Cart/Voucher/VoucherService.php
- tests/PHPUnit/Service/Cart/Voucher/VoucherServiceTest.php
easy coupon has products without an existing product number
lets do a soft-check instead of fail-fast
but we add a log notice at least
> MOL-666: Compatibility for EasyCoupon plugin

- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
- tests/Cypress/cypress/integration/storefront/payment-methods/creditcard.spec.js
The account order edit page does not have an id attribute on it's submit button, so the components would not get initialized.
> MOL-623: Change selector for confirm button

- src/Resources/views/storefront/component/buy-widget/buy-widget-form.html.twig
button was missing on custom cms pages that were created with CMS
this does now support the button in that widget too
> MOL-670: Apple Pay Direct missing on custom CMS PDP pages

- src/Facade/MolliePaymentDoPay.php
- src/Handler/PaymentHandler.php
- src/Resources/config/services.xml
- src/Service/CustomerService.php
- src/Service/MollieApi/Order.php
Payment specific parameters were not passed along to Mollie when creating a new payment after the first one failed.
> Fix payment specific params not being added to payment on reattempt

- src/Subscriber/OrderDeliverySubscriber.php
As discussed, I think there's a separate ticket for this to do it properly, this just disables the event.
> NTR: Quick disable shipping on delivery state change.

- src/Resources/app/administration/src/module/mollie-payments/components/mollie-tracking-info/index.js
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-tracking-info/mollie-tracking-info.html.twig
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-tracking-info/mollie-tracking-info.scss
- src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/index.js
- src/Resources/app/administration/src/module/mollie-payments/extension/sw-order/component/sw-order-line-items-grid/sw-order-line-items-grid.html.twig
- src/Resources/app/administration/src/snippet/de-DE.json
- src/Resources/app/administration/src/snippet/en-GB.json
- src/Resources/app/administration/src/snippet/nl-NL.json
Tracking codes that are available on the order are shown as clickable buttons. Clicking one will automatically fill the tracking info fields.
If only one tracking code is available it is automatically prefilled.
Tracking url from the shipping method is used to generate the correct url. If it's not available on the shipping method, it remains empty. 
A google query has been used as example
> MOL-719: Show existing trackingcodes and prefill tracking info

- tests/Cypress/cypress/integration/storefront/payment-methods/paypal.js
- tests/Cypress/cypress/support/actions/mollie/PaymentScreenAction.js
Added a copy of the banktransfer test to test PayPal's pending status
> MOL-721: Add Cypress test for PayPal pending status

- src/Resources/app/storefront/src/main.js
- src/Resources/views/storefront/component/payment/component/cc-fields.html.twig
- src/Resources/views/storefront/page/account/payment/index.html.twig
- src/Resources/views/storefront/page/checkout/confirm/index.html.twig
since Shopware 6.4.8.0 there is a console error on all pages.
the plugin did recently use IDs to bind the js plugins to the DOM
this however leads to an error in Shopware >= 6.4.8.0
so i've changed it to use data attributes
> MOL-742: Fix JS Plugin DOM binding for Shopware 6.4.8.0

- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-direct.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-payment-method.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components-sw64.plugin.js
- src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components.plugin.js
- src/Resources/app/storefront/src/mollie-payments/services/HttpClient.js
HttpClient has been updated to also allow POST. 
If the response is application/json it will auto parse it and return the parsed json object, otherwise it will just return the response body as is.
Callback functions are optional now.
All fetch statements have been removed from the Apple Pay JS plugins. 
The only other Promise in the Apple Pay Direct plugin has also been removed as IE also doesn't support those.
> MOL-724: Replace JS Fetch Command in Apple Pay Direct for IE

- src/Service/Payment/Provider/ActivePaymentMethodsProvider.php
Mollie throws an exception if the cart price is € 0.00, but not when it's € 0.01.
> MOL-754: Mollie limits throws exception

- src/Exception/MollieOrderCancelledException.php
- src/Exception/MollieOrderExpiredException.php
- src/Facade/MolliePaymentDoPay.php
- src/Service/MollieApi/Order.php
Orders usually expire after 28 days. There is a setting in the plugin configuration to set the expiration time to 1 day, but then you'd still have to wait a day testing.
It would be better to create a way to trigger a cancellation through the API.
Steps for testing:
1. Place an order in Shopware
2. Fail the payment on the payment screen
3. Cancel the order through the API, or set expiration time to 1 day and wait a day
4. Try to do the payment for the order in Shopware.
> MOL-611 Cannot create a new payment when a Mollie order is cancelled or expired.

- .infection.json
- makefile
Create logs of our infection testing to see where mutants escape. This might help us improve our testing.
For now lower the minimum MSI as 75% of our code is uncovered.
> Log escaped mutants so we can improve our tests

- src/Components/Subscription/Services/Builder/MollieDataBuilder.php
- src/Components/Subscription/SubscriptionManager.php
- src/Facade/Notifications/NotificationFacade.php
- src/Service/Mollie/MolliePaymentDetails.php
- src/Service/Mollie/OrderStatusConverter.php
- tests/PHPUnit/Components/Subscription/Services/Builder/MollieDataBuilderTest.php
- tests/PHPUnit/Service/Mollie/MolliePaymentDetailsTest.php
had to extract the mandateID from the paid payment that has been done
and reuse it when creating the subscription!
i did also rename the function into "buildPayload" because it makes more sense
and also added unit tests
> MOL-874: Use correct mandate ID of payment for subscription

- src/Components/Subscription/SubscriptionManager.php
- src/Controller/Api/Webhook/WebhookController.php
- src/Controller/Storefront/Webhook/WebhookController.php
- src/Repository/Order/OrderRepository.php
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
mollie also sends normal webhooks for subscriptions to this endpoint
so we need to check for existing orders and reuse this one
> MOL-904: Reuse existing orders in subscription webhooks

- src/Components/MollieLimits/Service/MollieLimitsRemover.php
- src/Service/Payment/Remover/CartAwareRouteInterface.php
Please also try this, should work for all payment method removers then. with only exception if we somehow dont have a cart object available.
> Added payment method api route to valid cart routes

- src/Facade/MolliePaymentDoPay.php
- src/Resources/config/services/facades.xml
- src/Resources/config/services/subscriber.xml
- src/Struct/Order/OrderAttributes.php
- src/Subscriber/WebhookTimezoneSubscriber.php
- tests/PHPUnit/Facade/MolliePaymentDoPayTest.php
- tests/PHPUnit/Subscriber/WebhookTimezoneSubscriberTest.php
Shopware reads the user's timezone from a cookie, and sets that in the twig environment. During webhook calls this cookie is unavailable, and will default to UTC.
To fix this we store the timezone in the order, and when webhooks are called we set this timezone on the twig environment.
> MOL-871: Webhook mails always have UTC time

- src/Struct/PaymentMethod/PaymentMethodAttributes.php
and prevent a fatal error if the `handlerIdentifier` of the payment method is not a valid class.
We currently experience this in combination with the stripe plugin:
> fix: Change method of checking if constant exists

- src/Service/MollieApi/Builder/MollieOrderAddressBuilder.php
- tests/PHPUnit/Service/MollieApi/Builder/MollieOrderAddressBuilderTest.php
It might happen that the salutation/title wrongfully contains whitespace only. This will lead to Mollie rejecting the order with 
```
Error executing API call (422: Unprocessable Entity): The ‘title’ field should not contain only whitespace characters.
```
To prevent this, we `trim()` the display name of the salutation.
> NTR: Ensure that `title` never contains whitespace only

- src/Compatibility/Bundles/FlowBuilder/Events/Checkout/OrderSuccessEvent.php
- src/Compatibility/Bundles/FlowBuilder/FlowBuilderEventFactory.php
- src/Compatibility/Bundles/FlowBuilder/Subscriber/BusinessEventCollectorSubscriber.php
- src/Facade/MolliePaymentFinalize.php
- src/Handler/PaymentHandler.php
- src/Resources/app/administration/src/snippet/de-DE.json
- src/Resources/app/administration/src/snippet/en-GB.json
- src/Resources/app/administration/src/snippet/nl-NL.json
- src/Resources/config/services/facades.xml
- src/Service/OrderService.php
option to create flow builder based on (storefront) checkout events
this helps to e.g. send order confirmation mails when the user comes back from Mollie
> NTR: add flow builder order success event

- src/Components/Subscription/Actions/CreateAction.php
@boxblinkracer Just wanted to add a debug message when no subscription was created.
Turns out we accidentally got rid of custom fields when persisting the cart, but mollie subscriptions depend on them. So it made sense for me to now have it in debug mode even if no subscription is created.
> NTR: add debug log when no subscription was created

- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/index.js
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/mollie-pluginconfig-section-order-lifetime-warning.twig
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/services/OderLifeTimeLimitDetectorService.js
- src/Resources/app/administration/src/module/mollie-payments/index.js
- src/Resources/app/administration/src/snippet/de-DE.json
- src/Resources/app/administration/src/snippet/en-GB.json
- src/Resources/app/administration/src/snippet/nl-NL.json
- src/Resources/app/administration/tests/components/mollie-pluginconfig-section-order-lifetime-warning/service/OderLifeTimeLimitDetectorService.spec.js
- src/Resources/config/config.xml
- tests/Cypress/cypress/e2e/admin/plugin-config.cy.js
- tests/Cypress/cypress/support/actions/admin/AdminPluginAction.js
This PR shows a warning if the order lifetime days is higher than 28, because Klarna has a limit of 28 days (could be higher depends on merchant)
And shows an error if there are more than 100 days
> MOL-1166: Show warning for high order lifetime days

- src/Subscriber/SystemConfigSubscriber.php
nwdxxItRechtConnector seems to create an entry without the salesChannelId, which is okay to do, but I get
```
[ErrorException]
Warning: Undefined array key "salesChannelId"
```
> Allow salesChannelId to be missing

- src/Compatibility/Bundles/FlowBuilder/Events/Refund/RefundStarted/RefundStartedEvent.php
- src/Compatibility/Bundles/FlowBuilder/Events/Refund/RefundStarted/RefundStartedEvent651.php
This allows the flow builder to access the refund amount, e.g. for customer mails.
Example in a mail template:
```
{{ amount | currency(order.currency.isoCode) }}
```
> Expose refund amount to flow.

- src/Service/Refund/Mollie/RefundMetadata.php
The quantity of a refund line item should not decide whether it will be included in the composition of the refund. Here is a scenario:
1. Let's say I have a line item in an order with a quantity of 1.
2. I issue a refund for said line item with quantity=1 and only half the amount.
3. The customer complains about my mistake and I come back to correct it.
Now I must issue a refund for the line item with the remaining amount, but I can only choose a quantity of 0. But that doesn't change the fact that this refund affects this line item and hence should list it in the composition.
FYI: My perspective on this is from an API consumer. So I consume the API provided by this plugin that will in turn consume the API of the Mollie platform.
> Include lineItems with quantity=0 in composition metadata

- src/Resources/config/services.xml
- src/Subscriber/CheckoutConfirmPageSubscriber.php
Here were some Problems
1) ideal issues, pos terminal and credit card mandate were loaded on every request
2) profile id was loaded twice, one general and one for ideal issues
now:
1) we load only additional data if mollie payments were selected
2) the profile id is loaded once and saved for the request
3) ideal, pos, CC data is loaded if the payment methods are selected
> MOL-1263: load data for selected payment methods only

- src/Resources/config/services/services.xml
- src/Service/Stock/StockManager.php
> MOL-1285: use stock manager config

- src/Controller/Storefront/Payment/MollieFailureControllerBase.php
- src/Facade/MolliePaymentFinalize.php
- src/Resources/config/compatibility/controller.xml
- src/Resources/config/compatibility/controller_6.5.xml
- src/Service/TransactionService.php
- tests/Cypress/cypress/e2e/storefront/subscriptions/subscription.cy.js
i know that the code is repeated, we have to comeup here with a better architecture, i would suggest to move if to refactoring after release?
> MOL-1280: Fix retry route and add cypress tests

- src/Resources/views/storefront/base.html.twig
- src/Subscriber/ApplePaySubscriber.php
> NTR: show mollie payment js if needed

- src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-payment-method.plugin.js
- tests/Cypress/cypress/e2e/storefront/payment-methods/applepay.cy.js
@boxblinkracer customer wants to select applay as default pament method in account area regardless of browser
> PISHPS-263: allow set apple pay as default payment method

- src/Components/RefundManager/Builder/RefundDataBuilder.php
- src/Components/RefundManager/RefundData/OrderItem/AbstractItem.php
- src/Components/RefundManager/RefundData/OrderItem/DeliveryItem.php
- src/Components/RefundManager/RefundData/OrderItem/ProductItem.php
- src/Components/RefundManager/RefundData/OrderItem/PromotionItem.php
- src/Components/RefundManager/RefundData/RefundData.php
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/grids/ShopwareOrderGrid.js
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/index.js
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/mollie-refund-manager.html.twig
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/mollie-refund-manager.scss
- src/Resources/app/administration/src/module/mollie-payments/components/mollie-refund-manager/services/RefundItemService.js
- src/Resources/app/administration/src/snippet/de-DE.json
- src/Resources/app/administration/src/snippet/en-GB.json
- src/Resources/app/administration/src/snippet/nl-NL.json
- tests/PHPUnit/Components/RefundManager/RefundData/OrderItem/ProductItemTest.php
- tests/PHPUnit/Components/RefundManager/RefundData/RefundDataTest.php
Add Flag to Refund Manager to automatically calculate Item Refund Value incl. VAT
This Flag is default off to not change default Behavior
This Flag also includes the Promotion VATs in the calculation, so that not more VAT is refunded than paid (as the promotion lowers the paid VAT)
> Mol 1299/refund tax at net orders

- polyfill/Shopware/Core/Checkout/Payment/Exception/PaymentProcessException.php
- polyfill/Shopware/Core/Checkout/Payment/PaymentException.php
- polyfill/Shopware/Core/Framework/Event/BusinessEventInterface.php
- polyfill/Shopware/Core/Framework/Event/CustomerAware.php
- polyfill/Shopware/Core/Framework/Event/FlowEventAware.php
- polyfill/Shopware/Core/Framework/Event/MailAware.php
- polyfill/Shopware/Core/Framework/Event/OrderAware.php
- polyfill/Shopware/Core/System/Snippet/Files/AbstractSnippetFile.php
- polyfill/Shopware/Core/System/Snippet/Files/SnippetFileInterface.php
A wrong class_exists call using a slash as namespace separator causing issues. The conditions are always false, regardless the Shopware classes exist.
> Fix namespace separator in polyfill classes

- src/Service/OrderDeliveryService.php
The change adds loading of the state-machine state to the loading of the order in `OrderDeliveryService`.
This is necessary, because otherwise the technical name of the state machine state can't be loaded here: https://github.com/mollie/Shopware6/blob/9558e0de87d0bc43190ae69242e9b1d77eb3e47b/src/Service/Transition/DeliveryTransitionService.php#L92 
This leeds to two delivery-state transitions: from shipped to open (see line 106) and then back to shipped (l. 109).
The second and third marked transition in the screenshot are caused by this bug.
I patched the file like in this PR, now it's working as intended
> fix: load order delivery state machine state

- src/Service/Router/RoutingBuilder.php
- tests/PHPUnit/Service/Routing/RoutingBuilderTest.php
I would suggest adapting the `applyCustomDomain` method to replace not just the host but the full base URL. This way you can also control the schema as well as any ports. 
In the current implementation you might run into the problem that you have a local port like `8000` which is not the case for the URL you want to replace it with. Then only the host is replaced, and Mollie will still try to access the new host on port `8000`, which is not what you want.
This changes the behaviour of the `MOLLIE_SHOP_DOMAIN` env variable a bit, because it should provide a schema. But it's not necessary.
> NTR - optimizes custom domain overwrite

- src/Service/Payment/Remover/CartAwareRouteInterface.php
- src/Service/Payment/Remover/OrderAwareRouteInterface.php
- src/Service/Payment/Remover/PaymentMethodRemover.php
so we had the problem of /atom.xml leading into exceptions and logs (bing-bot)
somehow it seems as if custom configurations lead to resolving of routes that shouldnt be resolved
then i think a bot detection or anything like this could lead to the route attribute being missing
nevertheless....our main goal here is just check if the route matching our expected cart or order routes
in that case it actually does not
so i think we should not have an impact in the exception chain in this case
so ive changed to fail-safe approaches
also removed the optional parameters because that leads to additional complexity and intertwining
> NTR: avoid misleading logs in payment remover route detection. fix #563

- src/Components/RefundManager/Elasticsearch/RefundAdminSearchIndexer.php
- src/Components/Subscription/Elasticsearch/SubscriptionAdminSearchIndexer.php
In v4.16.0 the array parameter offsets have been removed in the elasticsearch indexers.
- https://github.com/mollie/Shopware6/commit/af21146c500e3979be76b92e527e820275e70381#diff-d26dc687e8718b20bb95e47a76628023bbd0a3fa1de054c40ebaf3c0cbedfb39R86
- https://github.com/mollie/Shopware6/commit/af21146c500e3979be76b92e527e820275e70381#diff-cac2b867b0145eb6b7f855a93f5a2debd2751fdbd476e0ec068f3cfb37c3b58eR91
Due to this change the `bin/console dal:refresh:index` command fails with an `ErrorException`:
```
[ErrorException]                     
Warning: Array to string conversion 
```
This PR readds the the parameter offsets via `Doctrine\DBAL\Connection::ARRAY_PARAM_OFFSET` constant.
> Readd ARRAY_PARAM_OFFSET for parameter types in Elasticsearch indexers
